apiVersion: v1alpha1
kind: AnnotationSetting
metadata:
  generateName: annotation-setting-
spec:
  targetRef:
    group: core.halo.run
    kind: LinkGroup
  formSchema:
    - $formkit: text
      name: "icon"
      label: "图标"
      help: "图标名称，支持所有 iconify 图标。例如 https://icones.netlify.app/"
    - $formkit: checkbox
      name: "hide"
      label: "隐藏"
      value: "false"
      on-value: "true"
      off-value: "false"
---
apiVersion: v1alpha1
kind: AnnotationSetting
metadata:
  generateName: annotation-setting-
spec:
  targetRef:
    group: core.halo.run
    kind: Link
  formSchema:
    - $formkit: checkbox
      name: "hide"
      label: "隐藏"
      value: "false"
      on-value: "true"
      off-value: "false"
